# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0bcfc5ac419960120a27c6e7e0db0148358ec6d5fb9f46bda5c4d8b6aab6a42e8b7160b3444fa1c682cba5b0e5a7d055075c53282bc6f8cac5cd95b46f58141

test:
  secret_key_base: 2d1654eec27215fa3b626ccd59cdf58f284d8f13960800270b8a9a4402034cc1299d7d5c4608d72e8dce0b9923e41e97901af60428533bf5fce19305248a2263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
